
all: digitalization_organizations.pdf

digitalization_organizations.pdf: \
introduction.md \
action_actor.md \
action_organization.md \
reaction_actor.md \
reaction_organization.md \
digitalization_organizations.md
	bash md2pdf.sh digitalization_organizations
